/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;
import Main.Principal;
import java.awt.Color;

/**
 *
 * @author Alejandro Feria
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    String nombreProfesor = "";
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        panelInput = new javax.swing.JScrollPane();
        textInput = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        output = new javax.swing.JTextPane();
        boton = new javax.swing.JPanel();
        textoBoton = new javax.swing.JLabel();
        textProfesor = new javax.swing.JTextField();
        LabelFiltro = new javax.swing.JLabel();
        SeparatorProfesor = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textInput.setColumns(20);
        textInput.setRows(5);
        panelInput.setViewportView(textInput);

        bg.add(panelInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 400, 520));

        output.setFocusable(false);
        jScrollPane2.setViewportView(output);

        bg.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 420, 520));

        boton.setBackground(new java.awt.Color(150, 150, 150));
        boton.setForeground(new java.awt.Color(204, 204, 204));

        textoBoton.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        textoBoton.setForeground(new java.awt.Color(0, 0, 0));
        textoBoton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoBoton.setText("Convertir");
        textoBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textoBotonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textoBotonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textoBotonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout botonLayout = new javax.swing.GroupLayout(boton);
        boton.setLayout(botonLayout);
        botonLayout.setHorizontalGroup(
            botonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textoBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        botonLayout.setVerticalGroup(
            botonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textoBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        bg.add(boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 540, 120, 40));

        textProfesor.setBorder(null);
        textProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textProfesorActionPerformed(evt);
            }
        });
        bg.add(textProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, 240, -1));

        LabelFiltro.setBackground(new java.awt.Color(0, 0, 0));
        LabelFiltro.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        LabelFiltro.setText("Filtrar profesor");
        bg.add(LabelFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 230, -1));
        bg.add(SeparatorProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, 240, 10));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textoBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoBotonMouseClicked
        String input = textInput.getText();
        //System.out.println(input);
        
        //separar por saltos de linea
        String[] arrayLineas = input.split("\n");
        Principal principal = new Principal();
        //System.out.println("Nombre profesor: "+nombreProfesor);
        nombreProfesor = textProfesor.getText();

        output.setText(principal.leerInput(arrayLineas, nombreProfesor));
    }//GEN-LAST:event_textoBotonMouseClicked

    private void textProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textProfesorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textProfesorActionPerformed

    private void textoBotonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoBotonMouseEntered
        boton.setBackground(new Color(95, 95, 95));
        textoBoton.setForeground(new Color(240, 240, 240));
    }//GEN-LAST:event_textoBotonMouseEntered

    private void textoBotonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoBotonMouseExited
        boton.setBackground(new Color(150, 150, 150));
        textoBoton.setForeground(new Color(0, 0, 0));

    }//GEN-LAST:event_textoBotonMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelFiltro;
    private javax.swing.JSeparator SeparatorProfesor;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel boton;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane output;
    private javax.swing.JScrollPane panelInput;
    private javax.swing.JTextArea textInput;
    private javax.swing.JTextField textProfesor;
    private javax.swing.JLabel textoBoton;
    // End of variables declaration//GEN-END:variables
}
